namespace: default
resources:
- resources
vars:
- name: NFS_SERVER
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: nfs-provisioner-client-info
  fieldref:
    fieldpath: data.nfsServer
- name: NFS_PATH
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: nfs-provisioner-client-info
  fieldref:
    fieldpath: data.nfsPath
- name: NAMESPACE
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: nfs-provisioner-client-info
  fieldref:
    fieldpath: metadata.namespace
configurations:
- varreference.yaml
